apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
- name: metrics-server
  repo: https://kubernetes-sigs.github.io/metrics-server
  version: 3.11.0
  releaseName: metrics-server
  namespace: kube-system
  valuesFile: values.yaml