apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  labels:
    project: platform-tools
spec:
  project: platform-tools
  source:
    repoURL: https://git.edusuc.net/WEBFORX/ArgoCD-gitops
    targetRevision: HEAD
    path: TOOLS/metrics-server
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true