apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  labels:
    project: platform-tools
spec:
  project: platform-tools
  source:
    repoURL: https://github.com/la-belle-femme/532-Deploy-Metrics-Server-via-ArgoCD-using-Helm-Chart-and-kustomize.git
    targetRevision: main
    path: TOOLS/metrics-server
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
