apiService:
  create: true

args:
- --kubelet-insecure-tls
- --kubelet-preferred-address-types=InternalIP

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 50m
    memory: 100Mi

serviceMonitor:
  enabled: true
