apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference base configuration
resources:
  - ../../base

# Environment-specific name suffix
nameSuffix: -release

# Environment-specific patches
patchesStrategicMerge:
  - application-patch.yaml

# Environment-specific labels
commonLabels:
  environment: release
  deployment-branch: tags
  criticality: critical
  public-facing: "true"